homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('memories/', views.memories, name='memories'),
    path('smt3/', views.smt3, name='smt3'),
]

story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story_4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('/story-1', include('story_1.urls')),

]

homepage/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def memories(request):
    return render(request, 'memories.html')

def smt3(request):
    return render(request, 'smt3.html')

story_1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <title>Daijoubu?</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
      </head>
    <body>
      {% include "navbar.html" %}

    <div class="container" style="margin-bottom:20px">
      <div class="row">

        <div class="col-sm-4 col-md-4" style="margin-bottom:40px">
          <div class="cardname" style="padding-bottom: 20px; text-align: center;">
            <img src="{% static 'cardPhoto.jpg' %}" class="img-responsive img-rounded" alt="Responsive image">
            <h4 style="padding-bottom: 8px;">Ikmal Almuhtadi</h4>
            <h5><i>Sistem informasi</i></h5>
          </div>
          <hr class="rounded">
          <h3 style="text-align: center">My Current Favorite <p>Video Games</p></h3>
          <div class="gamelogo" style="margin-left: auto; margin-right: auto;">
            <img src="{% static 'game1.png' %}" class="img-responsive" alt="Responsive image">
            <br>
            <br>
            <img src="{% static 'game2.jpg' %}" class="img-responsive" alt="Responsive image">
          </div>
        </div>

        <div class="col-sm-8 col-md-8" style="padding-left: 30px;">
            <div class="aboutme">
                <h2>About Me>></h2>
                <p> I am an undergraduate student at University of Indonesia. 
                  I have a interest in gaming, travelling, and culinary topic. 
                  I also like to eat, a lot and one of my favorite dish is Wagyu 
                  Steak with creamy spinach.</p>
            </div>
            <br>
            <div class="experiences">
              <h2>Personal Experiences>></h2>
              <h4>Business Development Intern - <b>Hijrahfood</b></h4>
              <h4>VPIC of Operational - <b>PMB Fasilkom UI</b></h4>
              <h4>Staff of FnB Division - <b>COMPFEST 12</b></h4>
              <h4>Staff of Operational - <b>Wisuda Ganjil Fasilkom UI</b></h4>
            </div>
            <br>
            <div class="educations">
              <h2>Educations>></h2>
              <table id="edu" class="table-responsive table-borderless">
                <tbody>
                  <tr>
                    <td>SD Islam Al Azhar Jakapermai</td>
                    <td>:  2007 - 2013</td>
                  </tr>
                  <tr>
                    <td>SMP Negeri 109 Jakarta </td>
                    <td>:  2013 - 2016</td>
                  </tr>
                  <tr>
                    <td>SMA Negeri 5 Bekasi </td>
                    <td>:  2016 - 2019</td>
                  </tr>
                  <tr>
                    <td>Universitas Indonesia</td>
                    <td>:  2019 - 2023 (expected)</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <div class="contact">
              <h2>Contact me on <></h2>
              <table class="table-responsive table-borderless">
                <tbody>
                  <tr>
                    <td><a href="https://t.me/ikmalmuhtadi"target="_blank">
                      <img class="imge-responsive" src="{% static 'telegram.png' %}" hspace="25"/></a></td>
                      <td><a href="https://www.linkedin.com/in/ikmal-almuhtadi-bb87081a2/"target="_blank">
                      <img class="imge-responsive" src="{% static 'linkedin.png' %}" hspace="25"/></a></td>
                      <td><a href="https://www.instagram.com/ikmalmuhtadi/"target="_blank">
                      <img class="imge-responsive" src="{% static 'instagram.png' %}" hspace="25"/></a></td>
                      <td><a href="https://twitter.com/ikmalmuhtadi"target="_blank">
                      <img class="imge-responsive" src="{% static 'twitter.png' %}" hspace="25"/></a></td>
                  </tr>
                </tbody>
              </table>  
            </div>
        </div>

      </div>  
    </div>  

        <div class="footer footer-am">
          <div class="container">
            <p>Copyright © 2020 Ikmal.</p>
          </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </body>

</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <title>Daijoubu?</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
      </head>
    <body class="home">
        <div class="row" id="upper">
            <div class="col-md-12">
                <div class="text-center">
                    <img src="{% static 'logo.png' %}" id="krox" class="img-responsive img-rounded" alt="Responsive image">
                    <h1>Deeper.</h1>
                    <h1>Closer.</h1>
                </div>
            </div>
        </div>
        <br>
                        
        <div class="row" id="button">
            <div class="col-md-6 text-center">
                <a href="{% url 'homepage:about' %}" class="btn btn-default btn-lg" role="button">About Me</a>
            </div>
            <div class="col-md-6 text-center">
                <a href="{% url 'homepage:memories' %}" class="btn btn-default btn-lg" role="button">Memories</a>
            </div>
    
        </div>
        <br>
        <br>
        
        <div id="kotak" class="col-12 text-center">
            <p class="mini-p">Little Preview ☻</p>
            <div id="blur-p" class="row">
                <div class="col-md-4">
                    <img src="{% static 'blur1.JPEG' %}" class="img-responsive img-rounded" alt="Responsive image">
                </div>
                <div class="col-md-4">
                    <img src="{% static 'blur2.JPEG' %}" class="img-responsive img-rounded" alt="Responsive image">
                </div>
                <div class="col-md-4">
                    <img src="{% static 'blur3.JPEG' %}" class="img-responsive img-rounded" alt="Responsive image">
                </div>
            </div>
        </div>
        

        <div class="footer-h">
            <p>Copyright © 2020 Ikmal.</p>
        </div>




        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

homepage/templates/memories.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <title>Daijoubu?</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
      </head>
    <body>
      {% include "navbar.html" %}

          <div class="container">
            <div id="memories" class="row">
              <h2 style="text-align: center; padding-bottom: 30px;">Wonderful Times</h2>
              <div class="col-sm-4 col-md-4">
                <img src="{% static 'memories1.JPG' %}" class="img-responsive img-rounded" alt="Responsive image">
                <p style="padding-top: 20px;">Pentas seni Aftermath</p>
                <img src="{% static 'memories2.JPG' %}" class="img-responsive img-rounded" alt="Responsive image" style="margin-top: 60px;">
                <p style="padding-top: 20px;">Parade UI</p>
              </div>
              <div class="col-sm-4 col-md-4">
                <img src="{% static 'memories3.JPG' %}" class="img-responsive img-rounded" alt="Responsive image">
                <p style="padding-top: 20px;">Bakar-bakar pas tahun baru</p>
                <img src="{% static 'memories4.JPG' %}" class="img-responsive img-rounded" alt="Responsive image" style="margin-top: 60px;">
                <p style="padding-top: 20px;">Foto wajib maba UI</p>
              </div>
              <div class="col-sm-4 col-md-4">
                  <img src="{% static 'test2.jpg' %}" class="img-responsive img-rounded" alt="Responsive image" style="max-width:109%">
                  <p style="padding-top: 20px;">Pertama kali ketemu Salju :D</p>
                  <img src="{% static 'test1.jpg' %}" class="img-responsive img-rounded" alt="Responsive image" style="margin-top: 60px; max-width:103%">
                  <p style="padding-top: 20px;">Lab DDP2 terkocak</p>
              </div>
            </div>
          </div>

        <div class="footer footer-am">
          <div class="container">
            <p>Copyright © 2020 Ikmal.</p>
          </div>
        </div>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <title>Daijoubu?</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
      </head>

    <body>
        <nav class="navbar navbar-inverse navbar-expand-sm" style="background-color: black;">
            <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">
                    <img class="imge-responsive" src="{% static 'logo.png' %}" width="83" height="auto" alt="kroX">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'homepage:home' %}">Home</a></li>
                <li><a href="{% url 'homepage:about' %}">About Me</a></li>
                <li><a href="{% url 'homepage:memories' %}">Memories</a></li>
                <li><a href="{% url 'homepage:smt3' %}">Jadwal Kuliah</a></li>
                <li><a href="{% url 'story_1:story1' %}">Story-1</a></li>
            </ul>
            </div>
        </nav>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

homepage/templates/smt3.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <title>Daijoubu?</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
      </head>
    <body>
      {% include "navbar.html" %}

          <div class="container">
              <div class="row">
                  <div id="atas-smt3" class="col-sm-12 col-md-12">
                    <h2 style="text-align: center; padding-bottom: 30px;">Jadwal Kebahagiaan</h2>
                  </div>

                <div class="table table-responsive">
                  <table id="table-smt3" class="table table-borderless">
                    <thead>
                      <tr>
                        <th>Senin</th>
                        <th>Selasa</th>
                        <th>Rabu</th>
                        <th>Kamis</th>
                        <th>Jumat</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Agama <p><i>08.00 - 09.40</i></p></td>
                            <td>SDA <p><i>10.00 - 11.40</i></p></td>
                            <td>Adbis <p><i>08.00 - 10.30</i></p></td>
                            <td>SDA <p><i>10.00 - 11.40</i></p></td>
                            <td>PPM <p><i>08.00 - 10.30</i></p></td>
                        </tr>
                        <tr>
                            <td>DDAK <p><i>10.00 - 11.40</i></p></td>
                            <td>PPW <p><i>13.00 - 15.30</i></p></td>
                            <td>DDAK <p><i>14.00 - 15.40</i></p></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                  </table>
                </div>

              </div>
          </div>







        <div class="footer footer-am">
            <div class="container">
                <p>Copyright © 2020 Ikmal.</p>
            </div>
        </div>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

story_1/templates/story1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Daijoubu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .sansserif {
            font-family: Arial Black, sans-serif;
        }
        
        img {
            border-radius: 8px;
            
        }

        body {
          background-image: url('https://images.unsplash.com/photo-1575330719343-23de81f5b995?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1667&q=80');
          background-repeat: no-repeat;
          background-attachment: fixed; 
          background-size: cover;
        }
        hr.rounded {
          border-top: 8px solid #bbb;
          border-radius: 5px;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            width: 100%;
            border-radius: 5px;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

        .container {
            padding: 2px 16px;
        }
        * {
            box-sizing: border-box;
        }

        .column {
        float: left;
        padding: 10px;
        height: 475px;
        border-top: 8px;
        border-radius: 5px; 
        }

        .left {
        width: 25%;
        }

        .right {
        width: 75%;
        }

        .row:after {
        content: "";
        display: table;
        clear: both;
        }
        </style>
</head>
<body>
    {% include "navbar.html" %}
    
        <div id="main" class="sansserif" style="color:black; vertical-align:middle;margin:0px 100pxc">
             <h1> Hello, It's Me Again!</h1>
             <hr class="rounded">
        <div class="row">
            <div class="column left" style="background-color:white"> 
                <div class="card">
                    <img src="https://media-exp1.licdn.com/dms/image/C5603AQGBXJaQ6pcFHw/profile-displayphoto-shrink_400_400/0?e=1606348800&v=beta&t=z2STSIhLnOK34M3zv8TzsjzdbQp--Gqqh6DvKEXc0k8" alt="Avatar" style="width:100%">
                    <div class="container">
                    <h4>Ikmal Almuhtadi Rajab</h4> 
                    <p><b>Sistem Informasi</b></p> 
                    </div>
                </div>
            </div>

            <div class="column right" style="background-color:white;">
                <h2>Get to know me better</h2>
                <table style="width:60%;">
                    <tr>
                        <td><strong>Name :</strong></td>
                        <td>Ikmal Almuhtadi Rajab</td>
                    </tr>
                    <tr>
                        <td><strong>NPM :</strong></td>
                        <td>1906308324</td>
                    </tr>
                    <tr>
                        <td><strong>Student of :</strong></td>
                        <td>Fasilkom UI - 2019 <a href="https://maung.id/ikmal.almuhtadi" target="_blank">(Maung)</a></td>
                    </tr>
                    <tr>
                        <td><strong>Hobby :</strong></td>
                        <td>Gaming, any kind of Sports, and Travelling!</a></td>
                    </tr>
                    <tr>
                        <td><strong>Description :</strong></td>
                        <td>i like to eat, a lot.</a></td>
                    </tr>
                    <br>
                </table>
                <h2>Education</h2>
                <table style="width:60%;">
                <tr>
                    <td>SD Islam Al - Azhar 6 Jakapermai</td>
                        <td>2007 - 2013</td>
                    </tr>
                    <tr>
                        <td>SMP Negeri 109 Jakarta</td>
                        <td>2013 - 2016</td>
                    </tr>
                    <tr>
                        <td>SMA Negeri 5 Bekasi </td>
                        <td>2016 - 2019</td>
                    </tr>
                    <tr>
                        <td>University of Indonesia</td>
                        <td>2019 - 2023 <i>(expected)</i></td>
                    </tr>
                </table>
            </div>
        </div>
        
            <h2>Follow me on :</h2>
            <a href="https://www.instagram.com/ikmalmuhtadi/"target="_blank">
            <img src="https://instagram-brand.com/wp-content/themes/ig-branding/assets/images/ig-logo-email.png" width="50" height="50" hspace="20"/>
            </a>
            <a href="https://www.facebook.com/ikmal.almuhtadi"target="_blank">
                <img src="https://www.freepnglogos.com/uploads/facebook-logo-icon/facebook-logo-icon-file-facebook-icon-svg-wikimedia-commons-4.png" width="50" height="50" hspace="20"/>
            </a>
            <a href="https://www.linkedin.com/in/ikmal-almuhtadi-bb87081a2/"target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Linkedin.svg/1200px-Linkedin.svg.png" width="50" height="50" hspace="20"/>
            </a>
            <a href="https://twitter.com/ikmalmuhtadi"target="_blank">
                <img src="https://1000logos.net/wp-content/uploads/2017/06/Twitter-Logo.png" width="50" height="50" hspace="20"/>
            </a>
            

</body>
</html>